name:                stlc
version:             0.1.0.0
github:              "githubuser/stlc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/stlc#readme>

library:
  source-dirs: src
  default-extensions:
  - LambdaCase
  - GeneralizedNewtypeDeriving
  - BlockArguments
  dependencies:
  - base >= 4.7 && < 5
  - mtl
  - transformers
